3
# -*- coding: utf-8 -*-
"""System Test-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13D-4aj7XFEfTRwNtNUhRuqb-tHT75ggN
"""

#1
a=input()
print(a*3)

#2
a=input()
d="###"
print( a+ " "+d)

#4
a=input()
d=len(a)
print('*' * len(a))

#3
r="operator"
k=7
print((r +" ")*k)
#6
d=int(input())
g=d/100*300
print(float(g))

#7
length=int(input("enter length:"))
breadth=int(input("enter breadth:"))
perimeter=2*(length+breadth)
print("perimeter:",perimeter)

#5
g=float(input())
meters=g*1000
print(g)
print(int(meters))